site_name: setup.py
site_description: setup.py site_description

theme:
  name: "material"
  language: "zh"

repo_name: abersheeran/setup.py
repo_url: https://github.com/abersheeran/setup.py
edit_uri: ""

nav:
  - Get Start: "index.md"

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra
